### ISSUE TITLE
multiple small issues

### ISSUE THREAD

**Issue by cocoonkid** [SamuraiWTF/samuraiwtf#163]
Juice shop cannot be installed

```
ERROR Plugin 'get_url' suffered a critical failure: Could not find link pattern in resulting page.
usage: katanacli.py [-h] {list,install,remove,start,stop,status,lock} ...
```

vmware workstation related
```
had to install open-vm-tools-desktop  to make them work with vmware workstation 16.2
```
samurai-dojo appears to get installed but no change in ui same for juice shop as seen above

![image](https://user-images.githubusercontent.com/43231640/147077709-9eca8d42-126c-4bb7-b19d-3c1fe1b8b21a.png)

The  user samurai should be in  the docker group by default.

Everything else works like a charm. Thanks for this!

**Comment by mgillam** [comment]
Thanks for reporting @cocoonkid. A few of the targets have issues with the status UI. For some, it's related to not having a plugin yet for polling status on those particular targets, someone just needs to find time to write that.
I believe the Juice-Shop issue is because it moved to a different repo. This issue: https://github.com/SamuraiWTF/katana/issues/32

If you want to try manually fixing it in the mean time, it should be a matter of changing the URL in the following line: https://github.com/SamuraiWTF/katana/blob/master/modules/targets/juice-shop.yml#L11 
to `https://github.com/juice-shop/juice-shop/releases/latest`

I believe the Katana stuff is under the `/opt/samurai` directory, but I'm not totally sure on that off the of my head.

**Comment by cocoonkid** [comment]
Thanks so much! 

Had to change L11 and L13
```
      url: https://github.com/juice-shop/juice-shop/releases/latest
      link_pattern: \/juice-shop\/juice-shop\/releases\/download\/.*_node12_linux_x64.tgz
```
